name: aipnd-project
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.11,<3.15
  - torch>=2.9.1,<3.0
  - torchvision>=0.24.1,<0.25
  - numpy>=2.3.5,<3.0
  - matplotlib>=3.10.8,<4.0
  - pillow>=12.0.0,<13.0
  - tqdm>=4.67.1,<5.0
  - ipykernel>=7.1.0,<8.0